from evm import EVM
from bytecodes import *




GAS=21_000

# evm=EVM(SIMPLE_ADD,GAS,0)
# evm=EVM(SIMPLE_SUB,GAS,0)
# evm=EVM(SIMPLE_MUL,GAS,0)
# evm=EVM(SIMPLE_DIV,GAS,0)
# evm=EVM(SIMPLE_EXP,GAS,0)
# evm=EVM(SIMPLE_MOD,GAS,0)
# evm=EVM(ADD_OVERFLOW,GAS,0)
# evm=EVM(SUB_UNDERFLOW,GAS,0)
# evm=EVM(MUL_BY_ONE,GAS,0)
# evm=EVM(MUL_BIG_SMALL,GAS,0)
# evm=EVM(MUL_MAX,GAS,0)
# evm=EVM(DIV_BY_ZERO,GAS,0)
# evm=EVM(SIMPLE_SDIV,GAS,0)
# evm=EVM(SDIV_NEG_POS,GAS,0)
# evm=EVM(EXP_ZERO,GAS,0)
# evm=EVM(EXP_OVERFLOW,GAS,0)
# evm=EVM(ADDMOD_SIMPLE,GAS,0)
# evm=EVM(ADDMOD_ZERO_MOD,GAS,0)
evm=EVM(ADDMOD_OVERFLOW_10,GAS,0)


evm.run()


print(evm.stack)

